### PR TITLE
Configured project for publishing

### LINKED ISSUE #3: Configure project for publishing to npm
- compile to ES6
- include necessary files

### PR DESCRIPTION
**Pull request by rhysyngsun**
Fixes #3 

To test:

`docker-compose run web npm pack`

Then:
`tar tvf mdl-react-components-0.0.0.tgz`

should list the contents, you should only see `package.json`, the readme, license, and files in lib/

### CODE REVIEW

**Comment by aliceriot** [comment]
have you tried publishing the package under a beta tag so we can test and make sure it installs ok?

**Comment by rhysyngsun** [comment]
@aliceriot https://www.npmjs.com/package/@mitodl/mdl-react-components

**Comment by aliceriot** [comment]
looks like we may be missing a dependency?

dev_depencnenene

**Comment by aliceriot** [comment]
Tried adding it to open-discussions and it's working fine though, so maybe we don't need that? not sure

**Pull request merged**
